def evod(li):
    v1[]
    v2=[]
    n1=0
    n2=0
    for i in l:
        if i%2==0:
            v1.append(i)
            n1+=1
        else:
            v2.append(i)
            n2+=1
    print("The even numbers are {} and numbers:".format(n1))
    for i in v1:
        print(i)
-   print("The odd numbers are {} and numbers:".format(n2))
    for i in v2:
        print(i)

def crealist()
    vi=[]
    a=int(input("How many numbers you want to enter in list:"))
    for i in range(a):
        c=int(input("Enter a number:"))
        vi.append(c)
    evod(li)

crealist()